[toolchain]
# KEEP UP TO DATE with the `website` workflow!

# Embassy requires stable 1.75 and up
# setting 1.85.1 to use 2024 Edition as a baseline
channel = "1.85.1"


targets = ["thumbv6m-none-eabi", "riscv32imc-unknown-none-elf"]